-- ===========================================================================
--  Squad invite links — a coach (squad owner) mints a shareable link; anyone who
--  signs up / accepts with it joins the squad immediately (bypassing gating) and
--  it becomes their active squad. Run AFTER Squads.sql. Idempotent, safe to re-run.
--
--  A squad has at most one *active* (RevokedUtc IS NULL) link at a time; "reset"
--  revokes the current one and mints a fresh token. Tokens are url-safe random
--  strings generated by the app (see SqlSquadService.NewToken).
-- ===========================================================================
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

IF OBJECT_ID('dbo.SquadInvite', 'U') IS NULL
CREATE TABLE dbo.SquadInvite (
    Token       NVARCHAR(32)     NOT NULL,
    SquadId     UNIQUEIDENTIFIER NOT NULL,
    CreatedBy   UNIQUEIDENTIFIER NULL,                          -- the owner who created it
    CreatedUtc  DATETIMEOFFSET(0) NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    RevokedUtc  DATETIMEOFFSET(0) NULL,                         -- non-null ⇒ link disabled (reset)
    CONSTRAINT PK_SquadInvite PRIMARY KEY (Token),
    CONSTRAINT FK_SquadInvite_Squad FOREIGN KEY (SquadId) REFERENCES dbo.Squad (Id)
);

-- Fast lookup of a squad's active link (the "reuse existing" path when the coach
-- re-opens the invite panel).
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_SquadInvite_Squad_Active' AND object_id = OBJECT_ID('dbo.SquadInvite'))
CREATE INDEX IX_SquadInvite_Squad_Active ON dbo.SquadInvite (SquadId) WHERE RevokedUtc IS NULL;
